"""Add indexes for snippets table

Revision ID: a7cacfed7f68
Revises: 2233be826c0d
Create Date: 2025-01-23 15:46:39.811918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7cacfed7f68'
down_revision: Union[str, None] = '2233be826c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_snippets_language'), 'snippets', ['language'], unique=False)
    op.create_index(op.f('ix_snippets_owner_id'), 'snippets', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippets_owner_id'), table_name='snippets')
    op.drop_index(op.f('ix_snippets_language'), table_name='snippets')
    # ### end Alembic commands ###
